//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientosXFuncion
    {
        public int codAsiento { get; set; }
        public int codFuncion { get; set; }
        public string estado { get; set; }
        public Nullable<int> codDetalleVenta { get; set; }
        public Nullable<int> TipoDocAsociado { get; set; }
        public string DocAsociado { get; set; }
        public Nullable<double> PrecioPagado { get; set; }
        public byte[] concurrencia { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual Funcion Funcion { get; set; }
    }
}
