//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public Nullable<int> fila { get; set; }
        public Nullable<int> columna { get; set; }
        public int codAsiento { get; set; }
        public int codZona { get; set; }
    
        public virtual ZonaEvento ZonaEvento { get; set; }
    }
}
