//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int codDetalleVenta { get; set; }
        public int codVen { get; set; }
        public int codFuncion { get; set; }
        public int codPrecE { get; set; }
        public Nullable<int> cantEntradas { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> descTot { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> entradasDev { get; set; }
    
        public virtual PrecioEvento PrecioEvento { get; set; }
        public virtual VentasXFuncion VentasXFuncion { get; set; }
    }
}
