//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public DetalleVenta()
        {
            this.LogDevoluciones = new HashSet<LogDevoluciones>();
        }
    
        public int codDetalleVenta { get; set; }
        public int codVen { get; set; }
        public int codFuncion { get; set; }
        public int codPrecE { get; set; }
        public Nullable<int> cantEntradas { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> descTot { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> entradasDev { get; set; }
        public double montoDev { get; set; }
    
        public virtual PrecioEvento PrecioEvento { get; set; }
        public virtual VentasXFuncion VentasXFuncion { get; set; }
        public virtual ICollection<LogDevoluciones> LogDevoluciones { get; set; }
    }
}
