//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosPrueba
    {
        public int codEvento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<double> mAdeudado { get; set; }
        public Nullable<double> mTransferir { get; set; }
        public string lugar { get; set; }
        public Nullable<double> penCan { get; set; }
        public Nullable<double> penPost { get; set; }
        public Nullable<double> comision { get; set; }
        public Nullable<bool> esRecurrente { get; set; }
        public Nullable<bool> destacado { get; set; }
        public Nullable<System.DateTime> fechDev { get; set; }
        public Nullable<bool> esImpri { get; set; }
        public Nullable<bool> esReser { get; set; }
        public Nullable<int> maxReserva { get; set; }
        public Nullable<System.DateTime> limReserva { get; set; }
        public Nullable<int> codOrg { get; set; }
        public string codPromotor { get; set; }
        public Nullable<int> idRegion { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<bool> necDoc { get; set; }
        public Nullable<int> codLocal { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> cantPuntos { get; set; }
        public string urlDestacado { get; set; }
        public string urlImagen { get; set; }
        public string urlDistribucion { get; set; }
        public Nullable<int> codPreferencia { get; set; }
    }
}
