
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EventosPrueba
{

    public int codEvento { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public Nullable<System.DateTime> fechaFin { get; set; }

    public string estado { get; set; }

    public Nullable<System.DateTime> fechaInicio { get; set; }

    public Nullable<double> mAdeudado { get; set; }

    public Nullable<double> mTransferir { get; set; }

    public string lugar { get; set; }

    public Nullable<double> penCan { get; set; }

    public Nullable<double> penPost { get; set; }

    public Nullable<double> comision { get; set; }

    public Nullable<bool> esRecurrente { get; set; }

    public Nullable<int> destacado { get; set; }

    public Nullable<System.DateTime> fechDev { get; set; }

    public Nullable<bool> esImpri { get; set; }

    public Nullable<bool> esReser { get; set; }

    public Nullable<int> maxReserva { get; set; }

    public Nullable<System.DateTime> limReserva { get; set; }

    public int codOrg { get; set; }

    public string codPromotor { get; set; }

    public int idRegion { get; set; }

    public Nullable<int> idProvincia { get; set; }

    public bool necDoc { get; set; }

    public Nullable<int> codLocal { get; set; }

    public Nullable<int> idCategoria { get; set; }

    public Nullable<int> cantPuntos { get; set; }

    public string urlDestacado { get; set; }

    public string urlImagen { get; set; }

    public string urlDistribucion { get; set; }

    public Nullable<int> codPreferencia { get; set; }

}

}
