
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Local
{

    public Nullable<int> aforo { get; set; }

    public string ubicacion { get; set; }

    public string descripcion { get; set; }

    public int codLocal { get; set; }

    public Nullable<int> idProvincia { get; set; }

    public Nullable<int> idRegion { get; set; }



    public virtual Region Region { get; set; }

    public virtual Region Region1 { get; set; }

}

}
