//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDevoluciones
    {
        public int codLog { get; set; }
        public int codDetalleVenta { get; set; }
        public string codVendedor { get; set; }
        public Nullable<int> cantEntradas { get; set; }
        public Nullable<System.DateTime> fechaDev { get; set; }
        public Nullable<double> montoDev { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
        public virtual DetalleVenta DetalleVenta { get; set; }
    }
}
