
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Promociones
{

    public Nullable<System.DateTime> fechaIni { get; set; }

    public Nullable<System.DateTime> fechaFin { get; set; }

    public Nullable<float> descuento { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> cantAdq { get; set; }

    public Nullable<int> cantComp { get; set; }

    public string modoPago { get; set; }

    public Nullable<bool> estado { get; set; }

    public int codPromo { get; set; }

    public Nullable<int> codBanco { get; set; }

    public Nullable<int> codTipoTarjeta { get; set; }

    public int codEvento { get; set; }



    public virtual Banco Banco { get; set; }

    public virtual TipoTarjeta TipoTarjeta { get; set; }

}

}
