
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PuntoVenta
{

    public PuntoVenta()
    {

        this.Turno = new HashSet<Turno>();

    }


    public int codPuntoVenta { get; set; }

    public string ubicacion { get; set; }

    public Nullable<bool> estaActivo { get; set; }

    public string dirMAC { get; set; }



    public virtual ICollection<Turno> Turno { get; set; }

}

}
