//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regalo
    {
        public Regalo()
        {
            this.RegaloXCuenta = new HashSet<RegaloXCuenta>();
        }
    
        public int idRegalo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> puntos { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual ICollection<RegaloXCuenta> RegaloXCuenta { get; set; }
    }
}
