//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regalo
    {
        public Regalo()
        {
            this.RegaloXCuenta = new HashSet<RegaloXCuenta>();
        }
    
        public int idRegalo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> puntos { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual ICollection<RegaloXCuenta> RegaloXCuenta { get; set; }
    }
}
