
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication4.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Region
{

    public Region()
    {

        this.Local = new HashSet<Local>();

        this.Local1 = new HashSet<Local>();

        this.Region1 = new HashSet<Region>();

        this.Eventos = new HashSet<Eventos>();

    }


    public int idRegion { get; set; }

    public Nullable<int> idRegPadre { get; set; }

    public string nombre { get; set; }



    public virtual ICollection<Local> Local { get; set; }

    public virtual ICollection<Local> Local1 { get; set; }

    public virtual ICollection<Region> Region1 { get; set; }

    public virtual Region Region2 { get; set; }

    public virtual ICollection<Eventos> Eventos { get; set; }

}

}
