//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int codigo { get; set; }
        public string numTarjeta { get; set; }
        public string modoPago { get; set; }
        public int codTarjeta { get; set; }
        public int idTipoTar { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
    }
}
