//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        public int codigo { get; set; }
        public string numTarjeta { get; set; }
        public string modoPago { get; set; }
        public int codTarjeta { get; set; }
        public int idTipoTar { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
    }
}
