//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int codPuntoVenta { get; set; }
        public int codTurnoSis { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<double> MontoInicioSoles { get; set; }
        public Nullable<double> MontoInicioDolares { get; set; }
        public Nullable<double> MontoFinSoles { get; set; }
        public Nullable<double> MontoFinDolares { get; set; }
        public string estadoCaja { get; set; }
        public string horaRegistro { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual TurnoSistema TurnoSistema { get; set; }
    }
}
