//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasXFuncion
    {
        public VentasXFuncion()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int codVen { get; set; }
        public Nullable<int> cantEntradas { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<double> total { get; set; }
        public int codFuncion { get; set; }
    
        public virtual Ventas Ventas { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Funcion Funcion { get; set; }
    }
}
