//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.VentasXFuncion = new HashSet<VentasXFuncion>();
        }
    
        public int codVen { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantAsientos { get; set; }
        public Nullable<double> montoEfectivoSoles { get; set; }
        public Nullable<double> montoEfectivoDolares { get; set; }
        public Nullable<double> montoCreditoSoles { get; set; }
        public string modalidad { get; set; }
        public Nullable<int> tipoDoc { get; set; }
        public string codDoc { get; set; }
        public string cliente { get; set; }
        public string vendedor { get; set; }
        public string Estado { get; set; }
        public Nullable<double> MontoTotalSoles { get; set; }
        public int entradasDev { get; set; }
        public double montoDev { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
        public virtual CuentaUsuario CuentaUsuario1 { get; set; }
        public virtual ICollection<VentasXFuncion> VentasXFuncion { get; set; }
    }
}
