//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaEvento
    {
        public ZonaEvento()
        {
            this.Asientos = new HashSet<Asientos>();
            this.PrecioEvento = new HashSet<PrecioEvento>();
            this.Eventos1 = new HashSet<Eventos>();
        }
    
        public int codZona { get; set; }
        public int codEvento { get; set; }
        public string nombre { get; set; }
        public int aforo { get; set; }
        public bool tieneAsientos { get; set; }
        public Nullable<int> cantFilas { get; set; }
        public Nullable<int> cantColumnas { get; set; }
        public Nullable<int> idPrecioEvento { get; set; }
    
        public virtual ICollection<Asientos> Asientos { get; set; }
        public virtual Eventos Eventos { get; set; }
        public virtual ICollection<PrecioEvento> PrecioEvento { get; set; }
        public virtual ICollection<Eventos> Eventos1 { get; set; }
        public virtual PrecioEvento PrecioEvento1 { get; set; }
    }
}
