//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaxFuncion
    {
        public int codFuncion { get; set; }
        public int codZona { get; set; }
        public int cantLibres { get; set; }
        public byte[] concurrencia { get; set; }
        public int cantReservaOrganizador { get; set; }
    
        public virtual Funcion Funcion { get; set; }
        public virtual ZonaEvento ZonaEvento { get; set; }
    }
}
