//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaEvento
    {
        public ZonaEvento()
        {
            this.Asientos = new HashSet<Asientos>();
        }
    
        public int codZona { get; set; }
        public int codEvento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> piso { get; set; }
        public Nullable<int> aforo { get; set; }
        public int codLocal { get; set; }
    
        public virtual ICollection<Asientos> Asientos { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
