//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaxFuncion
    {
        public int codFuncion { get; set; }
        public int codZona { get; set; }
        public int cantLibres { get; set; }
        public byte[] concurrencia { get; set; }
        public int cantReservaOrganizador { get; set; }
    
        public virtual ZonaEvento ZonaEvento { get; set; }
        public virtual Funcion Funcion { get; set; }
    }
}
